### ISSUE TITLE
Add title of program to the install progress

### ISSUE THREAD

**Issue by Warniz** [hagaram/remote-magnet-link-handler#1]
Just an idea for the script to add the option to name the program, so if you don't want it named "remote magnet link handler" when the open application popup comes. F.eks. i renamed it to Transmission.

And thanks for the neat little script. Great work - Really glad I found it :)

**Comment by hagaram** [comment]
Hello, thank you for you suggestion!

Is this what you had in mind ? https://github.com/hagaram/remote-magnet-link-handler/commit/b5e87b7fad5f15fd5a9f3b8bee311329a44580f2 (line 102)

I'm glad the script was of use to you :)

**Comment by hagaram** [comment]
I suppose it is :). Once again, thank you for suggestion, it is available in the latest commit.
